---
language: python
services: docker

cache: pip

install:
  - pip install molecule[docker] yamllint ansible-lint docker

script:
  - molecule --version
  - molecule test -s python2
  - molecule test -s python3

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
