---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  # ubuntu
  - name: focal
    image: ubuntu:20.04
  - name: bionic
    image: ubuntu:18.04
  - name: xenial
    image: ubuntu:16.04
  # debian
  - name: buster
    image: debian:buster
  - name: stretch
    image: debian:stretch
  # centos
  - name: centos8
    image: centos:centos8
  - name: centos7
    image: centos:centos7

provisioner:
  name: ansible
  dockerfile: ../common/Dockerfile.j2
  playbooks:
    converge: ../common/converge.yml
    verify: ../common/verify.yml

verifier:
  name: ansible
